### PR TITLE
Upgrade to upstream 0.24.5

### PR DESCRIPTION
**Pull request by dcaliste**
This is an upgrade to upstream release 0.24.5. It brings various bugfixes.

It contains also a bump in soversion from .43.0.0 to .44.0.0. I don't know how to handle transition. Sailfish-office needs to be recompiled against this new library, but I don't know how to include it into SDK.

Besides, installing 0.24.5 in my phone, ignoring dependencies and making a link to .44.0.0 named .43.0.0, I've tested it and it works fine for various PDFs on my phone, including the reported PDFs that crashes before.

### CODE REVIEW

**Comment by pvuorela** [comment]
Appears this is missing upstream submodule update. Repository uses git subtree, so it needs some extra steps for upgrading. Compare with this: https://github.com/nemomobile-packages/maliit-framework/commits/master

**Comment by pvuorela** [comment]
Tried first to find some reference on the update scheme for these, but ended up just doing it :) https://github.com/nemomobile-packages/poppler/pull/4

For future reference, did:
cd upstream
git checkout poppler-0.24.5
cd ..
git commit -a -m "...."
git fetch upstream
git subtree pull --squash --prefix=poppler upstream HEAD

**Comment by dcaliste** [comment]
Ok, sorry didn't know about this. I'll follow this procedure next time ! Thanks for the explanations.

I will try later to follow this for a possible upgrade to 0.36.0.

**Comment by pvuorela** [comment]
As a detail, didn't end up having qt5 detection changes you had a revert commit for. But curiously git diff did point out Doxyfile PROJECT_NUMBER upgrades one mine.

**Comment by dcaliste** [comment]
I've checked that the Qt5 detection is find in your PR. I think it comes from the fact that it's a local commit before mine that has been kept. It was squash in my PR because I untar the tarball while it is kept in your case because you correctly import the commits between 0.24.0 and 0.24.5.

Well it's fine. Thanks for taking care of this.

**Pull request closed without merging**
