### PR TITLE
upgrade poppler to 0.36.0

### PR DESCRIPTION
**Pull request by pvuorela**
At least depending projects compile against this and sailfish-office keeps showing pdf files.

### CODE REVIEW

**Comment by dcaliste** [comment]
Great, thank you taking care of this !

**Comment by dcaliste** [comment]
I've compiled this PR without any issue, then installed it on my phone for several days already. I didn't notice anything strange with sailfish-office. No issue with password protected documents, no issue with previously crashing PDFs, no issue with my strange boarding pass from EasyJet (that adds random glyphs with poppler 0.18.4 on my old Ubuntu 12.04)…

I will keep it to continue testing, but everything seems OK.

**Comment by pvuorela** [comment]
Nice! I'll keep this open still for short while. Thinking of having the earlier update for one release and then pushing this for the next one.

**Comment by dcaliste** [comment]
That looks like a good strategy. Thanks.

**Comment by rainemak** [comment]
LGTM

**Pull request merged**
